// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLFP50q5vKjku1PTFuQhto69zhOifRwKM',
    appId: '1:860071283209:web:37eee5482f3f1ffcbd06d8',
    messagingSenderId: '860071283209',
    projectId: 'finance-tracker-app-94058',
    authDomain: 'finance-tracker-app-94058.firebaseapp.com',
    storageBucket: 'finance-tracker-app-94058.firebasestorage.app',
    measurementId: 'G-J5C9Z60XW6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaDxaSX9r6Q2pgVFhFrohoO5caVLji9Sg',
    appId: '1:860071283209:android:ee3f674d71188ccfbd06d8',
    messagingSenderId: '860071283209',
    projectId: 'finance-tracker-app-94058',
    storageBucket: 'finance-tracker-app-94058.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2r6gNmiHXHEgOClXzczJLIUL1gz6i1lc',
    appId: '1:860071283209:ios:67fa9e73b033871ebd06d8',
    messagingSenderId: '860071283209',
    projectId: 'finance-tracker-app-94058',
    storageBucket: 'finance-tracker-app-94058.firebasestorage.app',
    iosBundleId: 'com.example.financeTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2r6gNmiHXHEgOClXzczJLIUL1gz6i1lc',
    appId: '1:860071283209:ios:67fa9e73b033871ebd06d8',
    messagingSenderId: '860071283209',
    projectId: 'finance-tracker-app-94058',
    storageBucket: 'finance-tracker-app-94058.firebasestorage.app',
    iosBundleId: 'com.example.financeTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLFP50q5vKjku1PTFuQhto69zhOifRwKM',
    appId: '1:860071283209:web:72a8ca62e6f4ab6bbd06d8',
    messagingSenderId: '860071283209',
    projectId: 'finance-tracker-app-94058',
    authDomain: 'finance-tracker-app-94058.firebaseapp.com',
    storageBucket: 'finance-tracker-app-94058.firebasestorage.app',
    measurementId: 'G-QXEGTKTJ4S',
  );
}
